# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: name-tests-test
  # - repo: https://github.com/Lucas-C/pre-commit-hooks
  #   rev: v1.5.5
  #   hooks:
  #     - id: insert-license
  #       files: \.py$
  #       args: [
  #         '--license-filepath', 'LICENSE_HEADER.txt',
  #         '--comment-style', '',
  #         '--use-current-year',
  #         '--no-extra-eol',
  #       ]
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.0
    hooks:
      - id: poetry-check
      - id: poetry-lock
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.1
    hooks:
      - id: check-gitlab-ci
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff
  - repo: https://github.com/iamthefij/docker-pre-commit
    rev: v3.0.1
    hooks:
      - id: docker-compose-check
  - repo: local
    hooks:
      - id: hadolint
        name: 'Dockerfile Linting'
        description: 'Runs `hadolint` to lint Dockerfiles.'
        entry: hadolint
        args: ['--ignore', 'DL3008']
        language: system
        files: Dockerfile
      - id: gimtoc
        name: 'Generate Table of Contents'
        description: 'Runs `gimtoc` to generate a Table of Contents in README.md.'
        entry: gimtoc
        language: node
        files: README.md
        args: [
          '--file', 'README.md',
          '--section', 'Table of Contents',
          '--output', 'README.md',
        ]
      - id: autopep8
        name: 'Fix Python Code Style using AutoPEP8'
        description: 'Runs `autopep8` to format Python code.'
        entry: autopep8
        language: system
        files: '\.py$'
        args: [
          '--in-place',
          '--recursive',
          # Error codes: https://pycodestyle.pycqa.org/en/latest/intro.html#error-codes
          '--ignore', 'E1,E501',
        ]
      - id: pylint
        name: pylint
        entry: pylint
        language: python
        files: '\.py$'
        args:
          - "-rn" # Only display messages
          - "--errors-only"
          - "--ignore-paths=tests,.vscode,.gitlab"
