[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "oremi-ohunerin"
version = "4.0.0b1"
description = "Real-time ambient sound and wake word detection"
readme = "README.md"
requires-python = ">=3.11,<3.12"
license = { text = "Apache-2.0" }
authors = [
  { name = "Sébastien Demanou", email = "demsking@gmail.com" }
]
keywords = ["sound", "detection", "wakeword"]
classifiers = [
  "Environment :: Console",
  "Intended Audience :: Developers",
  "Natural Language :: English",
  "Natural Language :: French",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Programming Language :: Python :: 3.11",
]
dependencies = [
  "pocketsphinx>=5.0.4,<6.0.0",
  "numpy>=2.2.2,<3.0.0",
  "tflite-runtime>=2.13.0,<3.0.0",
  "tflite-support>=0.4.4,<0.5.0",
  "oremi-core>=2.5.3,<3.0.0",
  "pydantic>=2.11.1,<3.0.0",
]

[project.urls]
"Say Thanks!" = "https://www.buymeacoffee.com/demsking"
"Source" = "https://gitlab.com/demsking/oremi-ohunerin"
"Tracker" = "https://gitlab.com/demsking/oremi-ohunerin/-/issues"
"Documentation" = "https://gitlab.com/demsking/oremi-ohunerin/-/blob/main/README.md"

[project.scripts]
oremi-ohunerin = "ohunerin:main"

[dependency-groups]
dev = [
  "aiohttp>=3.9.0",
  "autopep8>=2.3.2",
  "bandit>=1.8.3",
  "classify-imports>=4.2.0",
  "pylint>=3.3.7",
  "pyroma>=4.2",
  "pytest>=8.3.5",
  "pytest-asyncio>=0.26.0",
  "pytest-cov>=6.1.1",
  "python-dotenv>=1.1.0",
  "python-slugify>=8.0.4",
  "reorder-python-imports>=3.14.0",
  "sounddevice>=0.5.5",
  "twine>=6.2.0",
]

[tool.hatch.build.targets.wheel]
packages = ["ohunerin"]

[tool.hatch.build]
ignore-vcs = true

[tool.pytest.ini_options]
# Function starting with the following pattern are considered for test cases.
python_functions = "test_"
