[flake8]
count = True
max-line-length = 120
ignore = E1,E501
in-place = True
recursive = True
statistics = True
aggressive = 3
indent-size = 2
hang_closing = False
max-complexity = 15

[pycodestyle]
ignore = E111,E114,E121,E501

# pydocstyle tool
# See https://www.pydocstyle.org/en/stable/usage.html#available-options
[pydocstyle]
ignore = D101,D102,D103,D212,D400
